### PR TITLE
fr-index.html fixes

### PR DESCRIPTION
**Pull request by trebmuh**
This fixes a mistake in translation and rename correctly the name of the file "_fr-index.html_" to "_1-fr-index.html_"
See https://github.com/jamulussoftware/jamuluswebsite/pull/47#issuecomment-732682832 (and below).

### CODE REVIEW

**Review by ann0see — APPROVED** [review]

**Comment by ann0see** [comment]
should we merge this?

**Comment by trebmuh** [comment]
@ann0see yes please.

**Comment by ann0see** [comment]
Done.

**Comment by trebmuh** [comment]
Thanks.

**Pull request merged**
