### PR TITLE
W: [fr] Command Line Options

### PR DESCRIPTION
**Pull request by gegeweb**
/ping @Saimyx @trebmuh

### CODE REVIEW

**Comment by gegeweb** [comment]
Ready for review

**Comment by trebmuh** [comment]
There was too much stuff to be changed for a review.
I've made another PR with the fixes applied.

_Note: the most frustrating in this PR here is that you're keeping adding stuff in the French translation which aren't in the original version. Don't do that. Open a PR against the EN version first. And it'll go down in the translation._

**Comment by gegeweb** [comment]
Sorry, I think I've missed to recheck correctly against the EN version if it is the case.
I could take a look again before you're comments.
That's on of the page translated before clarify the rules.

**Comment by trebmuh** [comment]
Feel free to make comment on #89 now please.

**Comment by gegeweb** [comment]
> Feel free to make comment on #89 now please.

Done.

My apologies again, please wait for the fix commit.

**Comment by trebmuh** [comment]
No need for a commit fix. Just review and approve #89 and that'll be good.

**Comment by ann0see** [comment]
Please reopen and merge into main.

**Comment by trebmuh** [comment]
@ann0see why so? This one has been superseded by #89 which have been merged into "translation-3.6.1" branch. So why would we want to merge this PR which contains a lot of errors/mistakes/typos/... while the one without those has already been merged in #89? Doing so would add errors in the translation.

**Comment by ann0see** [comment]
Ah. Sorry. I didn't notice that. (I just copy and pasted my answer to a few french PRs).

**Comment by gegeweb** [comment]
I'll not resubmit this. ;) I think that is just a mistake.

**Comment by ann0see** [comment]
Yes. It was a mistake...

**Comment by trebmuh** [comment]
OK, no worries. I just thought it was weird. :wink:

**Pull request closed without merging**
