### PR TITLE
Some minor changes I propose for the next version

### PR DESCRIPTION
**Pull request by ann0see**
Despite that we should rethink:
* Do we need the feel free to add your own demos on the demos page?
* the getting started page especially the audio interface section to reduce stressing the USB microphone

Like #52 but now the right branch

### CODE REVIEW

**Review by gilgongo — APPROVED** [review]
Looks good - nice!

**Comment by ann0see** [comment]
You can then probably merge it

**Comment by gilgongo** [comment]
OK

**Comment by ann0see** [comment]
Ok. Thanks!

**Pull request merged**
