### PR TITLE
W: [fr] Server Win Mac

### PR DESCRIPTION
**Pull request by gegeweb**
/ping @Saimyx @trebmuh

### CODE REVIEW

**Comment by gegeweb** [comment]
I'll fix #88 here.
Wait for the feedback and conclusion about this issue before merging.
Reviewing can be start for the other points (wait for the new commit before starting)

**Comment by gegeweb** [comment]
@trebmuh Do I going back to keep close to the EN, or are we waiting for the discussion and the fix on the EN about the issues above?

**Comment by trebmuh** [comment]
Wait for the discussion and the fix on the EN version first.

**Comment by gegeweb** [comment]
> Wait for the discussion and the fix on the EN version first.

Last commit to be in sync with en actual EN version.

**Pull request closed without merging**
