### PR TITLE
Compiling: add qtconcurrent as (Gentoo) dependency

### PR DESCRIPTION
**Pull request by hoffie**
qmake fails with the following message otherwise:
```
$ qmake "CONFIG+=nosound headless " Jamulus.pro
Project MESSAGE: Headless mode activated.
Project ERROR: Unknown module(s) in QT: concurrent
```

### CODE REVIEW

**Comment by ann0see** [comment]
Yeah. I added this for Debian too. It seems to be a new dependency. 

@gilgongo can we merge that or do we have to wait till the freeze is over?

**Comment by gilgongo** [comment]
I'm not sure if we resolved exactly how we'd be doing documentation changes other than saying we'd do them all prior to each software release. I'm keeping a list in a Google doc for the moment (and will add this). But what are the options?

1. Somebody collects up all the PRs that we want to action (some might not be ones we want), mails the translators with the list of PRs to look at.

2. Collect up all the PRs we want to do and make a single issue describing all the changes in a way that makes is easy for translators to do.

3. Don't tell people to raise PRs (although they can if they want I guess) and tell them to suggest changes as issues, then do 2.

4. Some other method?

**Comment by hoffie** [comment]
As I read it there is some process re-design about doc PRs. Once agreement has been reached, updating `CONTRIBUTING.md` and the `Edit this site` on the bottom of each page might want updating. :)

Let me know if I should do anything different in my PR.

Thanks for creating and working on this software, by the way. Looks really promising! Looking forward to trying it out with my choral group in the coming days. :)

**Comment by ann0see** [comment]
Any updates on this @gilgongo?

**Comment by gilgongo** [comment]
If the dependency is universal (not just Gentoo) we need to know what the package names are for other distros. I don't seem to be able to reproduce this dependency for them though. On Ubuntu at least is seems to be added automatically with one of the other QT packages but I'm not sure. We can put it in the Gentoo statement for now though.

**Comment by ann0see** [comment]
For me this dependency was also needed for jamulus to run (headless and with gui).

**Comment by gilgongo** [comment]
OK so I'm assuming this is libqt5concurrent5 on both Debian and Ubuntu, so adding that.

**Comment by ann0see** [comment]
I think it's already part of the compilation dependencies but not for running jamulus without compilation on a machine.

**Comment by gilgongo** [comment]
This is now in the translation-3.6.1 branch (sorry, we're just sorting out the process). Can I therefore close this?

**Comment by ann0see** [comment]
I ran build-debian-package.sh and dpkg-shlibdeps says that this was a useless dependency:

"dpkg-shlibdeps: Warnung: Das Paket könnte eine nutzlose Abhängigkeit vermeiden, falls debian/jamulus-headless/usr/bin/jamulus-headless nicht gegen libQt5Concurrent.so.5 gelinkt wäre (es verwendet keines der Symbole der Bibliothek).
dpkg-shlibdeps: Warnung: Das Paket könnte eine nutzlose Abhängigkeit vermeiden, falls debian/jamulus/usr/bin/jamulus nicht gegen libGL.so.1 gelinkt wäre (es verwendet keines der Symbole der Bibliothek).
dpkg-shlibdeps: Warnung: Das Paket könnte eine nutzlose Abhängigkeit vermeiden, falls debian/jamulus/usr/bin/jamulus nicht gegen libQt5Concurrent.so.5 gelinkt wäre (es verwendet keines der Symbole der Bibliothek).
"

which basically means that libGL.so doesn't have to be linked. @corrados should have a look at this.

**Comment by ann0see** [comment]
@Saimyx have you also considered this change?

**Comment by hoffie** [comment]
> This is now in the translation-3.6.1 branch (sorry, we're just sorting out the process). Can I therefore close this?

Fine with me, the change seems to have made it to the website already. Maybe @ann0see still wants it open due to the debian dependency analysis? Leaving it up to you. :)

**Comment by ann0see** [comment]
You can close it. I will open a new issue on the main repo about that.

**Pull request closed without merging**
