### PR TITLE
Update en-Installation-for-Macintosh.md

### PR DESCRIPTION
**Pull request by trebmuh**
It was sounding strange/incomplete to my ears.
Hence, I made this proposition.

### CODE REVIEW

**Comment by ann0see** [comment]
Assigned gilgongo since it's the english version.

**Comment by ignotus666** [comment]
Just a small correction:

"...which will create a new folder with **the** same name."

**Comment by trebmuh** [comment]
Correct. Thanks @ignotus666 .

**Review by gilgongo — APPROVED** [review]

**Comment by trebmuh** [comment]
@gilgongo @ann0see who is the one able to merge this commit?

**Comment by ann0see** [comment]
We can both merge it. 

But the process is still to be discussed.

**Pull request merged**
