### PR TITLE
JACK/Jack : consistency around the English pages

### PR DESCRIPTION
**Pull request by trebmuh**
Hi, I've saw a bit of a mix between the way it's written in the different pages.

JACK is an acronym (a recursive one) meaning: JACK Audio Connection Kit.
Hence here is a first argument to keep it written in capital letter.
Another argument is that it helps with disambiguating "JACK" the software, and "jack" an audio cable (guitar,...).

Here is a PR for the few occurrences fixes I found around the English pages.

HTH

### CODE REVIEW

**Comment by trebmuh** [comment]
Pinging @gilgongo since it's changes against the English pages.

**Comment by gegeweb** [comment]
A good practice for acronym is ton enclose it inside a `<abbr>` tag with a title like this for JACK:

```html
<abbr title="JACK Audio Connection Kit">JACK</abbr>
```

**Comment by trebmuh** [comment]
I'm not against the idea.
Can you please open another issue for that? This one is about a fix for "JACK/Jack : consistency around the English pages" because there are a few inconsistency so far, while you're proposing something new.
Thanks.

**Comment by gilgongo** [comment]
Good idea - I'll merge this and then we can put the tags in.

**Comment by trebmuh** [comment]
Thanks for the quick merge. Very appreciated.

**Pull request merged**
