### PR TITLE
W: [all] same as #65, fix #64

### LINKED ISSUE #64: [Bug] Incorrect structure for navigation
As you can see in the screenshot below (using w3m) a new list item is created after the `h3`title.
The 'li' should not be closed after the 'h3' and not reopeened before the unordered list for submenu.

Capture d’écran 2020-11-24 à 13 14 34

Here is the output of the good structure (I'll open a MR) with the fix below:
Capture d’écran 2020-11-24 à 13 57 13

Capture d’écran 2020-11-24 à 14 15 43

```html
<aside id="gnav" class="fx-col-100-xs fx-col-25-m">
	{% include langselect.html %}
	<nav id="mnv">
		<ul>
			{% if site.data.navigation.nav[0] %} {% for item in site.data.navigation.nav %} {% if item.url %}
			<li>
				<h3><a href="{{ item.url | relative_url }}" class="{% if subentry.url == page.url %}selected{% endif %}">{{ item.title }}</a></h3>
				{% else %}
				<li>
					<h3>{{ item.title }}</h3>
					{% endif %} {% if item.subfolderitems[0] %}
					<ul>
						{% for entry in item.subfolderitems %}
						<li><a href="{{ entry.url }}" class="{% if entry.url == page.url %}selected{% endif %}">{{ entry.page }}</a> {% if entry.subsubfolderitems[0] %}
							<ul>
								{% for subentry in entry.subsubfolderitems %}
								<li><a href="{{ subentry.url }}" class="{% if subentry.url == page.url %}selected{% endif %}">{{ subentry.page }}</a></li>
								{% endfor %}
							</ul>
							{% endif %}
						</li>
						{% endfor %}
					</ul>
				</li>
				{% endif %} {% endfor %} {% endif %}
		</ul>
	</nav>
</aside>
```

### PR DESCRIPTION
**Pull request by gegeweb**
Same as #65 merged in `changes`branch.

/ping @ann0see

### CODE REVIEW

**Comment by ann0see** [comment]
I think we should use a cherry pick rather than a new pr)

**Comment by gegeweb** [comment]
> I think we should use a cherry pick rather than a new pr)

I don't know what is a cherry pick. If it is better, I can close this PR.

**Comment by ann0see** [comment]
It's basically a "please merge only this commit into this branch" command. But I think it's not even needed since the main branch already has this change. So if we merge translation into main there won't be a conflict also since it's also in changes it will be part of the next translation.

**Comment by gegeweb** [comment]
OK, I close.
Not yet used to working with multiple branches like here. ;)

**Pull request closed without merging**
