### PR TITLE
W: [all] fix #64

### LINKED ISSUE #64: [Bug] Incorrect structure for navigation
As you can see in the screenshot below (using w3m) a new list item is created after the `h3`title.
The 'li' should not be closed after the 'h3' and not reopeened before the unordered list for submenu.

Capture d’écran 2020-11-24 à 13 14 34

Here is the output of the good structure (I'll open a MR) with the fix below:
Capture d’écran 2020-11-24 à 13 57 13

Capture d’écran 2020-11-24 à 14 15 43

```html
<aside id="gnav" class="fx-col-100-xs fx-col-25-m">
	{% include langselect.html %}
	<nav id="mnv">
		<ul>
			{% if site.data.navigation.nav[0] %} {% for item in site.data.navigation.nav %} {% if item.url %}
			<li>
				<h3><a href="{{ item.url | relative_url }}" class="{% if subentry.url == page.url %}selected{% endif %}">{{ item.title }}</a></h3>
				{% else %}
				<li>
					<h3>{{ item.title }}</h3>
					{% endif %} {% if item.subfolderitems[0] %}
					<ul>
						{% for entry in item.subfolderitems %}
						<li><a href="{{ entry.url }}" class="{% if entry.url == page.url %}selected{% endif %}">{{ entry.page }}</a> {% if entry.subsubfolderitems[0] %}
							<ul>
								{% for subentry in entry.subsubfolderitems %}
								<li><a href="{{ subentry.url }}" class="{% if subentry.url == page.url %}selected{% endif %}">{{ subentry.page }}</a></li>
								{% endfor %}
							</ul>
							{% endif %}
						</li>
						{% endfor %}
					</ul>
				</li>
				{% endif %} {% endfor %} {% endif %}
		</ul>
	</nav>
</aside>
```

### PR DESCRIPTION
**Pull request by gegeweb**
Fix the structure of navigation menu : don not close and reopen 'li' after the 'h3'.

### CODE REVIEW

**Comment by trebmuh** [comment]
Why changing the indentation?
It makes it hard to read and review this PR and it (probably) breaks consistency across the repo.

**Comment by gegeweb** [comment]
> Why changing the indentation?

Because vscode settings and no `.editorconfig` in this repository.

Otherwise: "_thanks for the correction, could you try to restore the original indentation? We can better identify the changes._"
Was much more pleasant and nice to read.

Hope last commit will do the job.

Have a good late afternoon.

**Comment by trebmuh** [comment]
> Otherwise: "thanks for the correction, could you try to restore the original indentation? We can better identify the changes." Was much more pleasant and nice to read.

It looks to me that you are over-interpreting things when I'm writing.
I've asked a question, and explain why I asked it.
There is no offence to be read in that.

**Comment by ann0see** [comment]
By the way @gegeweb thanks for the pr. 

To all: I am a bit busy at the moment and had to focus on other things ;-) too. 
There's no .editorconfig yet, but I think we can add it. I agree that the contribution process is a bit messy but we're just building it up. @gegeweb Already provided a Contributing file which we should discuss and publish on the repo soon n

**Pull request merged**
